In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("human_vital_signs_dataset_2024.csv")
df.head()

,Patient ID,Heart Rate,Respiratory Rate,Timestamp,Body Temperature,Oxygen Saturation,Systolic Blood Pressure,Diastolic Blood Pressure,Age,Gender,Weight (kg),Height (m),Derived_HRV,Derived_Pulse_Pressure,Derived_BMI,Derived_MAP,Risk Category
0,1,60,12,2024-07-19 21:53:45.729841,36.861707,95.702046,124,86,37,Female,91.541618,1.679351,0.121033,38,32.459031,98.666667,High Risk
1,2,63,18,2024-07-19 21:52:45.729841,36.511633,96.689413,126,84,77,Male,50.704921,1.992546,0.117062,42,12.771246,98.000000,High Risk
2,3,63,15,2024-07-19 21:51:45.729841,37.052049,98.508265,131,78,68,Female,90.316760,1.770228,0.053200,53,28.821069,95.666667,Low Risk
3,4,99,16,2024-07-19 21:50:45.729841,36.654748,95.011801,118,72,41,Female,96.006188,1.833629,0.064475,46,28.554611,87.333333,High Risk
4,5,69,16,2024-07-19 21:49:45.729841,36.975098,98.623792,138,76,25,Female,56.020006,1.866419,0.118484,62,16.081438,96.666667,High Risk

In [2]:
df.info()
df.describe()
df['Risk Category'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200020 entries, 0 to 200019
Data columns (total 17 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Patient ID                200020 non-null  int64
 1   Heart Rate                200020 non-null  int64
 2   Respiratory Rate          200020 non-null  int64
 3   Timestamp                 200020 non-null  object
 4   Body Temperature          200020 non-null  float64
 5   Oxygen Saturation         200020 non-null  float64
 6   Systolic Blood Pressure   200020 non-null  int64
 7   Diastolic Blood Pressure  200020 non-null  int64
 8   Age                       200020 non-null  int64
 9   Gender                    200020 non-null  object
 10  Weight (kg)               200020 non-null  float64
 11  Height (m)                200020 non-null  float64
 12  Derived_HRV               200020 non-null  float64
 13  Derived_Pulse_Pressure    200020 non-null  int64
 14  Derived_BMI               200020 non-null  float64
 15  Derived_MAP               200020 non-null  float64
 16  Risk Category             200020 non-null  object
dtypes: float64(7), int64(7), object(3)
memory usage: 25.9+ MB

Risk Category
High Risk    105115
Low Risk      94905
Name: count, dtype: int64

In [3]:
feature_cols = [
    'Heart Rate',
    'Respiratory Rate',
    'Body Temperature',
    'Oxygen Saturation',
    'Systolic Blood Pressure',
    'Diastolic Blood Pressure',
    'Age',
    'Weight (kg)',
    'Height (m)',
    'Derived_HRV',
    'Derived_Pulse_Pressure',
    'Derived_BMI',
    'Derived_MAP',
    'Gender'
]

In [4]:
df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 0})

In [5]:
df

,Patient ID,Heart Rate,Respiratory Rate,Timestamp,Body Temperature,Oxygen Saturation,Systolic Blood Pressure,Diastolic Blood Pressure,Age,Gender,Weight (kg),Height (m),Derived_HRV,Derived_Pulse_Pressure,Derived_BMI,Derived_MAP,Risk Category
0,1,60,12,2024-07-19 21:53:45.729841,36.861707,95.702046,124,86,37,0,91.541618,1.679351,0.121033,38,32.459031,98.666667,High Risk
1,2,63,18,2024-07-19 21:52:45.729841,36.511633,96.689413,126,84,77,1,50.704921,1.992546,0.117062,42,12.771246,98.000000,High Risk
2,3,63,15,2024-07-19 21:51:45.729841,37.052049,98.508265,131,78,68,0,90.316760,1.770228,0.053200,53,28.821069,95.666667,Low Risk
3,4,99,16,2024-07-19 21:50:45.729841,36.654748,95.011801,118,72,41,0,96.006188,1.833629,0.064475,46,28.554611,87.333333,High Risk
4,5,69,16,2024-07-19 21:49:45.729841,36.975098,98.623792,138,76,25,0,56.020006,1.866419,0.118484,62,16.081438,96.666667,High Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200015,200016,87,17,2024-03-03 00:18:46.246950,37.058905,95.357470,120,84,75,1,63.496314,1.848268,0.129698,36,18.587394,96.000000,Low Risk
200016,200017,76,16,2024-03-03 00:17:46.246950,36.463631,99.340786,131,89,76,1,99.384322,1.988074,0.061232,42,25.145064,103.000000,Low Risk
200017,200018,81,13,2024-03-03 00:16:46.246950,36.665477,98.120530,124,89,18,0,71.771830,1.918059,0.097381,35,19.508780,100.666667,Low Risk
200018,200019,83,13,2024-03-03 00:15:46.246950,37.019873,95.362426,125,86,66,0,60.220388,1.861655,0.068300,39,17.375810,99.000000,High Risk
200019,200020,69,14,2024-03-03 00:14:46.246950,37.012931,99.523058,133,78,67,0,91.442825,1.853322,0.096521,55,26.622442,96.333333,Low Risk

In [6]:
risk_map = {
    'Low Risk': 0.2,
    'High Risk': 0.8
}

df['Deterioration_Score'] = df['Risk Category'].map(risk_map)

In [7]:
df[['Risk Category', 'Deterioration_Score']].head()

  Risk Category  Deterioration_Score
0     High Risk                  0.8
1     High Risk                  0.8
2      Low Risk                  0.2
3     High Risk                  0.8
4     High Risk                  0.8

In [8]:
df = df.dropna(subset=feature_cols + ['Deterioration_Score'])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200020 entries, 0 to 200019
Data columns (total 18 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Patient ID                200020 non-null  int64
 1   Heart Rate                200020 non-null  int64
 2   Respiratory Rate          200020 non-null  int64
 3   Timestamp                 200020 non-null  object
 4   Body Temperature          200020 non-null  float64
 5   Oxygen Saturation         200020 non-null  float64
 6   Systolic Blood Pressure   200020 non-null  int64
 7   Diastolic Blood Pressure  200020 non-null  int64
 8   Age                       200020 non-null  int64
 9   Gender                    200020 non-null  int64
 10  Weight (kg)               200020 non-null  float64
 11  Height (m)                200020 non-null  float64
 12  Derived_HRV               200020 non-null  float64
 13  Derived_Pulse_Pressure    200020 non-null  int64
 14  Derived_BMI               200020 non-null  float64
 15  Derived_MAP               200020 non-null  float64
 16  Risk Category             200020 non-null  object
 17  Deterioration_Score       200020 non-null  float64
dtypes: float64(8), int64(8), object(2)
memory usage: 27.5+ MB

In [10]:
X = df[feature_cols]
y = df['Deterioration_Score']

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [13]:
# from sklearn.ensemble import RandomForestRegressor

# rf = RandomForestRegressor(
#     n_estimators=100,
#     random_state=42
# )

# rf.fit(X_train_scaled, y_train)

In [14]:
# from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# y_pred_baseline = rf.predict(X_test_scaled)

# mse = mean_squared_error(y_test, y_pred_baseline)
# mae = mean_absolute_error(y_test, y_pred_baseline)
# r2 = r2_score(y_test, y_pred_baseline)

# print("Baseline RandomForest:")
# print("MSE:", mse)
# print("MAE:", mae)
# print("R2:", r2)

In [16]:
from sklearn.preprocessing import MinMaxScaler

scaler_mm = MinMaxScaler()
X_train_mm = scaler_mm.fit_transform(X_train)
X_test_mm = scaler_mm.transform(X_test)

In [17]:
def logistic_map_transform(X, r=3.7):
    """
    X: numpy array of shape (n_samples, n_features) with values in [0,1]
    r: chaos parameter (3.5–4 is common for chaotic behavior)
    """
    return r * X * (1 - X)

In [18]:
X_train_chaos = logistic_map_transform(X_train_mm, r=3.7)
X_test_chaos = logistic_map_transform(X_test_mm, r=3.7)

In [20]:
from sklearn.ensemble import RandomForestRegressor
rf_chaos = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf_chaos.fit(X_train_chaos, y_train)

RandomForestRegressor(random_state=42)

In [21]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
y_pred_chaos = rf_chaos.predict(X_test_chaos)

mse_c = mean_squared_error(y_test, y_pred_chaos)
mae_c = mean_absolute_error(y_test, y_pred_chaos)
r2_c = r2_score(y_test, y_pred_chaos)

print("Chaos-based RandomForest:")
print("MSE:", mse_c)
print("MAE:", mae_c)
print("R2:", r2_c)

Chaos-based RandomForest:
MSE: 0.027343667533246675
MAE: 0.0911169383062058
R2: 0.6954989100771138

In [23]:
results = pd.DataFrame({
    'True Score': y_test.values,
    # 'Baseline Pred': y_pred_baseline,
    'Chaos Pred': y_pred_chaos
})

results.head()

   True Score  Chaos Pred
0         0.8       0.464
1         0.2       0.200
2         0.2       0.200
3         0.8       0.800
4         0.2       0.200

In [24]:
results

       True Score  Chaos Pred
0             0.8       0.464
1             0.2       0.200
2             0.2       0.200
3             0.8       0.800
4             0.2       0.200
...           ...         ...
39999         0.8       0.800
40000         0.2       0.200
40001         0.8       0.752
40002         0.2       0.200
40003         0.2       0.200

[40004 rows x 2 columns]

In [25]:
def risk_band(score):
    if score < 0.3:
        return "Low"
    elif score < 0.6:
        return "Medium"
    else:
        return "High"

results['Chaos_Risk_Level'] = results['Chaos Pred'].apply(risk_band)

In [26]:
results

       True Score  Chaos Pred Chaos_Risk_Level
0             0.8       0.464           Medium
1             0.2       0.200              Low
2             0.2       0.200              Low
3             0.8       0.800             High
4             0.2       0.200              Low
...           ...         ...              ...
39999         0.8       0.800             High
40000         0.2       0.200              Low
40001         0.8       0.752             High
40002         0.2       0.200              Low
40003         0.2       0.200              Low

[40004 rows x 3 columns]

In [27]:
import joblib

# assuming these exist from your training code:
# scaler_mm  -> MinMaxScaler (fit on windowed X)
# rf_chaos   -> RandomForestRegressor (chaos-based model)

joblib.dump(scaler_mm, "scaler_minmax.pkl")
joblib.dump(rf_chaos, "chaos_regressor.pkl")

print("Saved scaler_minmax.pkl and chaos_regressor.pkl")

Saved scaler_minmax.pkl and chaos_regressor.pkl